   /*
 * Project name:
     CHi_Hub_VGCLD.vglcd
     
     Misc functions I need for project
     
 * Generated by:
     Mike
 * Date of creation
     4/11/2016
 * Time of creation
     9:26:56 PM
 * Test configuration:
     MCU:             P18F87K22
     Dev.Board:       SmartGLCD240x128_hw_rev_1.51
     Oscillator:      48000000 Hz
     SW:              mikroC PRO for PIC
                      http://www.mikroe.com/eng/products/view/7/mikroc-pro-for-pic/
 */

#include "CHi_Hub_VGCLD_objects.h"
#include "Misc_functions.h"
#include "global_defs.h"
#include "built_in.h"

// RF Files
#include "RF_registers.h"
#include "RF_ReadWrite_Routines.h"
#include "RF_Reset_Routines.h"
#include "RF_Misc_Routines.h"
#include "RF_Init_Routines.h"


// extern variables
extern uint8_t  g_send_bind_with_flash, g_send_bind_no_flash, g_send_flash;
extern union params_t EEParams;  // Set up the Params structure

// Timers..
extern volatile uint16_t heartbeat_tmr, open_close_tmr;

// LEDs
extern sfr sbit BacklightBlue;
extern sfr sbit BacklightRed;
extern sfr sbit BacklightGreen;

// buzzer
// Buzzer
sbit Buzzer_Direction at TRISJ7_bit;
sbit Buzzer_Out at LATJ7_bit;

void My_Init(void)
{
     // Set up PWM on Blue LED (PWM3)
     //PWM3_Init(3000); // Start at lowest freq with 48MHz clock
     //PWM3_Set_Duty(64); // Dim to start
     //PWM3_Start();
     
     // Set up PWM - we are using ECCP3 PWM - Uses Timer 3/4 (CCPTMRS0)
     BLUE_DUTY_CYCLE = 64; // 25% duty cycle - Mapped to CCPR3L
     CCPTMRS0 = 0b01000000;  // Map to timer 4
     PR4 = 0xFF; // Period register - lowest frequency
     CCP3CON = 0b00001111; // Single output, Lower duty cycle = 0, PWM Mode A is active low
     T4CON = 0xFF; // 1:16 post scale, timer on, 1:16 Prescale in
     TMR4IP_bit = 1; // High priority (default)
     PSTR3CON = 0b00010001; // STR signal control output, Sync on PWM Period, Only A output
     
     // Set up timer 1 to give 10ms interrupt
     // set up and fire off the timer - Use Timer 0
     //T0CON = 0b11000111; // Timer on, 8 bit, use internal clock, use prescaler, /256  - This workd for XTAL <= 16Mhz
     // Above 16 Mhz, need 16 bit timer
     //T0CON = 0b10000110;  // Timer On, 16 bit, Internal Clock, use prescaler, /128
     //TMR0IF_bit = 0; // reset flag
     //TMR0L = 0;
     //TMR0H = 250;
     //TMR0IP_bit = 0; // Set to Low Priority
     //TMR0IE_bit = 0; // don't enable yet
     
     // Set up Timer 5
     //void InitTimer5(){
     T5CON         = 0x10; // Not turned on yet
     TMR5IF_bit         = 0;
     TMR5H         = 0x15;
     TMR5L         = 0xA0;
     TMR5IP_bit  = 0;  // low priority
     TMR5IE_bit         = 1;
     //INTCON         = 0xC0;
     //}
     
     // Set up the buzzer
       Buzzer_Direction = 0;
       Buzzer_Out = 0;
     
     // Enable Interrupts
     // Interupts (INTCON, RCON Reg)
     //INTEDG0 = 0; INT0IF = 0; INT0IE = 1; // Enable INT0 - Air1 on Neg Edge, Always high Priority
     //INT1IP = 1; INTEDG1 = 0; INT1IF = 0; INT1IE = 1; // Enable INT1 - Air2 on Neg Edge, High Priority
     IPEN_bit = 1; // Enable Priority interrupts
     GIEH_bit = 1; // Enable high priority interrupts
     GIEL_bit = 1; // enable low priority interrupts
     
     // Stuff in default TP cal constants
     TP_Set_Calibration_Consts(EEParams.HubParams.TP_Cals[0], EEParams.HubParams.TP_Cals[1], EEParams.HubParams.TP_Cals[2], EEParams.HubParams.TP_Cals[3]);

}      // End My Init

void Display_Cals()
{
     unsigned int tp_xmin, tp_xmax, tp_ymin, tp_ymax;
     char strtemp[20];
     char numstr[7];
     
     // Display Cal constants
    T6963C_grFill(0);                                        // Clear display
    T6963C_txtFill(0);
    T6963C_Set_Font_Adv(T6963C_defaultFont, T6963C_WHITE, _T6963C_HORIZONTAL);
    TP_Get_Calibration_Consts(&tp_xmin, &tp_xmax, &tp_ymin, &tp_ymax);
    IntToStr(tp_xmin, numstr);
    strcpy(strtemp,"X Min: ");
    strcat(strtemp,numstr);
    T6963C_Write_Text_Adv(strtemp, 13, 30);
    IntToStr(tp_xmax, numstr);
    strcpy(strtemp,"X max: ");
    strcat(strtemp,numstr);
    T6963C_Write_Text_Adv(strtemp, 13, 40);
    IntToStr(tp_ymin, numstr);
    strcpy(strtemp,"Y Min: ");
    strcat(strtemp,numstr);
    T6963C_Write_Text_Adv(strtemp, 13, 50);
    IntToStr(tp_ymax, numstr);
    strcpy(strtemp,"Y Max: ");
    strcat(strtemp,numstr);
    T6963C_Write_Text_Adv(strtemp, 13, 60);
}

void Write_Cals(void)
{
    unsigned int tp_xmin, tp_xmax, tp_ymin, tp_ymax;
    
    TP_Get_Calibration_Consts(&tp_xmin, &tp_xmax, &tp_ymin, &tp_ymax);
    EEParams.HubParams.TP_Cals[0] = tp_xmin; // Xmin
    EEParams.HubParams.TP_Cals[1] = tp_xmax; // Xmax
    EEParams.HubParams.TP_Cals[2] = tp_ymin; // Ymin
    EEParams.HubParams.TP_Cals[3] = tp_ymax; // Ymax
    // Now write them back out to the EEPROM
    Write_params(EEParams.Params_Array);
}

// I had to copy their calibrate and make it my function, couldn't access theirs...
//
// ***************************************
void My_Calibrate_TP() {
  char i;
  unsigned int tp_xmin, tp_xmax, tp_ymin, tp_ymax;
  do{
     i=0;
     BacklightRed = 0;
     BacklightGreen = 0;
     BLUE_DUTY_CYCLE = 255; // Full white
     T6963C_grFill(0);                                        // Clear display
     T6963C_txtFill(0);
     T6963C_Set_Font_Adv(T6963C_defaultFont, T6963C_WHITE, _T6963C_HORIZONTAL);
     T6963C_Write_Text_Adv("CALIBRATION", 80, 60);
    Delay_ms(1000);
    T6963C_grFill(0);                                        // Clear display
    T6963C_txtFill(0);

    T6963C_dot(0,127,T6963C_WHITE);  // Draw bottom left dot
    T6963C_Write_Text_Adv("TOUCH BOTTOM LEFT", 13, 50);
    TP_Calibrate_Bottom_Left();          // Calibration of bottom left corner
    Delay_ms(500);

    T6963C_dot(0,127,T6963C_BLACK);                                        // Clear bottom left dot
    T6963C_Set_Font_Adv(T6963C_defaultFont, T6963C_BLACK, _T6963C_HORIZONTAL);
    T6963C_Write_Text_Adv("TOUCH BOTTOM LEFT", 13, 50);
    T6963C_dot(239,0,T6963C_WHITE);                                       // Draw upper right dot
    T6963C_Set_Font_Adv(T6963C_defaultFont, T6963C_WHITE, _T6963C_HORIZONTAL);
    T6963C_Write_Text_Adv("TOUCH UPPER RIGHT", 20, 13);
    TP_Calibrate_Upper_Right();                              // Calibration of upper right corner

    Delay_ms(500);
    T6963C_grFill(0);                                        // Clear display
    T6963C_txtFill(0);
    Display_Cals();  // Write to Screen
    // Check they are in range
    TP_Get_Calibration_Consts(&tp_xmin, &tp_xmax, &tp_ymin, &tp_ymax);
    if((tp_xmin<100) || (tp_xmin>300)) i=1;
    if((tp_xmax<3700) || (tp_xmax>3900)) i=1;
    if((tp_ymin<300) || (tp_ymin>500)) i=1;
    if((tp_ymax<3500) || (tp_ymax>3700)) i=1;
    if(i==1)
    {
       // error
       BacklightRed = 0;
       BacklightGreen = 1;
       BLUE_DUTY_CYCLE = 0; // turn to red
       Delay_ms(5000);
    }
    else
    {
        Delay_ms(2000);
    }
    T6963C_grFill(0);                                        // Clear display
    T6963C_txtFill(0);
  
  } while (i == 1);
}

// read in the params out of EEProm
void Read_params(unsigned char *ptr)
{
    // Check for new part
    unsigned int i;
    for(i=0; i<NUMEEPARAMS; i++)
    {
        // Read the eeprom
        *ptr++ = EEPROM_Read( i+CHAIR_PARAMS_ADDRESS );  // Expects unsigned Int as argument
    }
}

// Write in the params out of EEProm
void Write_params(unsigned char *ptr)
{
    // Write out params
    unsigned int i;
    for(i=0; i<NUMEEPARAMS; i++)
    {
        // Write the eeprom
        EEPROM_Write( i+CHAIR_PARAMS_ADDRESS, *ptr++ );
        while(WR_bit); // wait for done        EECON1.WR
    }
}

void Toggle_Send_RF_Bind_with_Flash() {
    // Toggles sending of the Bind with Flash command
    static uint8_t f_send; // Flag to indicate if suppose to send or not
    if(0 == f_send)
    {
        // we were off, turn in on
        f_send = 1;
        g_send_bind_with_flash = 1; // set global variable for checking
        // Disable all other buttons on this Screen - even the back button
        bSetReclineLimit.Active = 0;
        bChangePW.Active = 0;
        bDimLevel.Active = 0;
        bNext2Admin2.Active = 0;
        bBindNoFlash.Active = 0;
        bChairDim.Active = 0;
        bAdminReturn.Active = 0;
        
        bSetReclineLimit.Visible = 0;
        bChangePW.Visible = 0;
        bDimLevel.Visible = 0;
        bNext2Admin2.Visible = 0;
        bBindNoFlash.Visible = 0;
        bChairDim.Visible = 0;
        bAdminReturn.Visible = 0;
        bBindFlash.Caption = "Stop Sending";
        DrawScreen(&ScreenAdmin1);
        
        //Change color to indicate sending
        BacklightRed = 0;
        BacklightGreen = 1;
        BLUE_DUTY_CYCLE = 0; // off
        // BacklightBlue = 1; // Set PWM for blue to off
    }
    else
    {
        // we were on, turn it off
        f_send = 0;
        g_send_bind_with_flash = 0; // clear global variable for checking
        // Enable all other buttons on this Screen
        bSetReclineLimit.Active = 1;
        bChangePW.Active = 1;
        bDimLevel.Active = 1;
        bNext2Admin2.Active = 1;
        bBindNoFlash.Active = 1;
        bChairDim.Active = 1;
        bAdminReturn.Active = 1;
        
        bSetReclineLimit.Visible = 1;
        bChangePW.Visible = 1;
        bDimLevel.Visible = 1;
        bNext2Admin2.Visible = 1;
        bBindNoFlash.Visible = 1;
        bChairDim.Visible = 1;
        bAdminReturn.Visible = 1;
        bBindFlash.Caption = "Sync with Flash";
        DrawScreen(&ScreenAdmin1);
        //Change color back to normal
        BacklightRed = 1;
        BacklightGreen = 1;
        BLUE_DUTY_CYCLE = EEParams.HubParams.Backlight_Level; // set the duty cycle Register - that's why it's in CAPS - it's a define
    }
}

void Toggle_Send_RF_Bind_no_Flash() {
    // Toggles sending of the Bind with NO Flash command
    static uint8_t f_send; // Flag to indicate if suppose to send or not
    if(0 == f_send)
    {
        // we were off, turn in on
        f_send = 1;
        g_send_bind_no_flash = 1; // set global variable for checking
        // Disable all other buttons on this Screen - even the back button
        bSetReclineLimit.Active = 0;
        bChangePW.Active = 0;
        bDimLevel.Active = 0;
        bNext2Admin2.Active = 0;
        bBindFlash.Active = 0;
        bChairDim.Active = 0;
        bAdminReturn.Active = 0;

        bSetReclineLimit.Visible = 0;
        bChangePW.Visible = 0;
        bDimLevel.Visible = 0;
        bNext2Admin2.Visible = 0;
        bBindFlash.Visible = 0;
        bChairDim.Visible = 0;
        bAdminReturn.Visible = 0;
        bBindNoFlash.Caption = "Stop Sending";
        DrawScreen(&ScreenAdmin1);

        //Change color to indicate sending
        BacklightRed = 0;
        BacklightGreen = 1;
        BLUE_DUTY_CYCLE = 0; // off
        // BacklightBlue = 1; // Set PWM for blue to off
    }
    else
    {
        // we were on, turn it off
        f_send = 0;
        g_send_bind_no_flash = 0; // clear global variable for checking
        // Enable all other buttons on this Screen
        bSetReclineLimit.Active = 1;
        bChangePW.Active = 1;
        bDimLevel.Active = 1;
        bNext2Admin2.Active = 1;
        bBindFlash.Active = 1;
        bChairDim.Active = 1;
        bAdminReturn.Active = 1;

        bSetReclineLimit.Visible = 1;
        bChangePW.Visible = 1;
        bDimLevel.Visible = 1;
        bNext2Admin2.Visible = 1;
        bBindFlash.Visible = 1;
        bChairDim.Visible = 1;
        bAdminReturn.Visible = 1;
        bBindNoFlash.Caption = "Sync no Flash";
        DrawScreen(&ScreenAdmin1);
        //Change color back to normal
        BacklightRed = 1;
        BacklightGreen = 1;
        BLUE_DUTY_CYCLE = EEParams.HubParams.Backlight_Level; // set the duty cycle Register - that's why it's in CAPS - it's a define
    }
}

void Send_RF_Broadcast_Cmd_n(char n_times)
{
   static n=0; // num times to send out command
   // Gets called every 100ms...
   // First test if the incoming n_times is zero - if so, send out if counter not at zero
   if(n_times == 0)
   {
       // They just want us to check and send out command if not expired
       if(n != 0)
       {
          // still have some times to send it out...
          n--;
          write_TX_normal_FIFO_variable(); // Data_buf[] global should already be set up . This will send it out the radio too...
       }
   }
   else
   {
       // set up to start sending
       n = n_times;
       n--;
       heartbeat_tmr = 0; // reset timer
       write_TX_normal_FIFO_variable(); // Data_buf[] global should already be set up . This will send it out the radio too...
   }
}

void SendRF_Command_CLOSE_ALL(void)
{
     // This will send the close all command, as long as the timer is above the sending time..
     // First check if we can send the command...
     if(open_close_tmr > OPEN_CLOSE_RESEND_TIME)
     {
          // OK to send
          send_broadcast_message(CMD_CLOSE_ALL);
          open_close_tmr = 0;  // Reset timer
     }
} // end Send Close ALL

void SendRF_Command_OPEN_ALL(void)
{
     // This will send the close all command, as long as the timer is above the sending time..
     // First check if we can send the command...
     if(open_close_tmr > OPEN_CLOSE_RESEND_TIME)
     {
          // OK to send
          send_broadcast_message(CMD_OPEN_ALL);
          open_close_tmr = 0;  // Reset timer
     }
} // end Send Open ALL

void SendRF_Command_OPEN_FOOTREST_ALL(void)
{
     // This will send the close all command, as long as the timer is above the sending time..
     // First check if we can send the command...
     if(open_close_tmr > OPEN_CLOSE_RESEND_TIME)
     {
          // OK to send
          send_broadcast_message(CMD_FOOT_OPEN_ALL);
          open_close_tmr = 0;  // Reset timer
     }
} // end Send Open ALL

void Toggle_Send_Flash() {
    // Toggles sending of the Flash Chairs command
    static uint8_t f_send; // Flag to indicate if suppose to send or not
    if(0 == f_send)
    {
        // we were off, turn in on
        f_send = 1;
        g_send_flash = 1; // set global variable for checking
        // Disable all other buttons on this Screen - even the back button
        bCalTouch.Active = 0;
        bAdminReturn2.Active = 0;
        bDisplayCals.Active = 0;
        bEnableKidLock.Active = 0;
        bDisableKidLock.Active = 0;

        bCalTouch.Visible = 0;
        bAdminReturn2.Visible = 0;
        bDisplayCals.Visible =0;
        bEnableKidLock.Visible = 0;
        bDisableKidLock.Visible = 0;
        bFlashChair.Caption = "Stop Sending";
        DrawScreen(&ScreenAdmin2);
        //Change color to indicate sending
        BacklightRed = 0;
        BacklightGreen = 1;
        BLUE_DUTY_CYCLE = 0; // off
        // BacklightBlue = 1; // Set PWM for blue to off
    }
    else
    {
        // we were on, turn it off
        f_send = 0;
        g_send_flash = 0; // clear global variable for checking
        // Enable all other buttons on this Screen
        bCalTouch.Active = 1;
        bAdminReturn2.Active = 1;
        bDisplayCals.Active=1;
        bEnableKidLock.Active = 1;
        bDisableKidLock.Active = 1;

        bCalTouch.Visible = 1;
        bAdminReturn2.Visible = 1;
        bDisplayCals.Visible =1;
        bEnableKidLock.Visible = 1;
        bDisableKidLock.Visible = 1;
        bFlashChair.Caption = "Flash All Chairs";
        DrawScreen(&ScreenAdmin2);
        //Change color back to normal
        BacklightRed = 1;
        BacklightGreen = 1;
        BLUE_DUTY_CYCLE = EEParams.HubParams.Backlight_Level; // set the duty cycle Register - that's why it's in CAPS - it's a define
    }
} // end send flash

void Display_Hub_Address()
{
    // displays the hubs address
    // may want to add clearing display, setting mode, etc if not called from Display_Cals function that
    // already had set this up....
    char strtemp[32];
    char i, num2hex[4];

    //T6963C_grFill(0);                                        // Clear display
    //T6963C_txtFill(0);
    //T6963C_Set_Font_Adv(T6963C_defaultFont, T6963C_WHITE, _T6963C_HORIZONTAL);
    strcpy(strtemp,"Hub Addr:  ");
    for(i=8; i>0; i--)
    {
       // read EE, convert to Hex
       //ByteToHex(EEPROM_Read(i-1), num2hex);   // Put hex in num2hex string
       ByteToHex(EEParams.HubParams.MyLongAddress[i-1], num2hex);   // Put hex in num2hex string
       strcat(strtemp, num2hex); // add to string
    }
    T6963C_Write_Text_Adv(strtemp, 13, 90);
   
} // end Display Hub Address

void Beep()
{
   // Beeps to indicate key press
   uint8_t i;
   for(i=0; i<250; i++)
   {
      Buzzer_Out = 1;
      Delay_us(140);
      Buzzer_Out = 0;
      Delay_us(140);
   }
} // End Beep